### ISSUE TITLE
Executing CCSegProcess

### ISSUE THREAD

**Issue by mortaza-afshani** [chrisadamsonmcri/CCSegThickness#5]
Hi Chris,
I hope you are fine. I get an error as I run the CCSegProcess. The error is as following:

```
Traceback (most recent call last):
  File "CCSegProcess", line 368, in <module>
    main()
  File "CCSegProcess", line 227, in main
    CCSegPipeMidSag.midsagExtract(os.path.join(inputDirectory, curSubject), outputBase, MSPMethod, doGraphics = doGraphics, skullStripped = skullStripped, useMNIBrainMask = useMNIBrainMask)
  File "/home/mafshani/Desktop/CCSegThickness-master/CCSegPipeMidSag.py", line 211, in midsagExtract
    NIIShape = NII.get_shape()
  File "/home/mafshani/anaconda3/lib/python3.8/site-packages/nibabel/deprecator.py", line 181, in deprecated_func
    raise error_class(message)
nibabel.deprecator.ExpiredDeprecationError: get_shape method is deprecated.
Please use the ``img.shape`` property instead.

* deprecated from version: 1.2
* Raises <class 'nibabel.deprecator.ExpiredDeprecationError'> as of version: 3.0
```

**Comment by chrisadamsonmcri** [comment]
Fixed in 7d2e86e6bea03b565932f47d61232f129238ce64
